### ISSUE TITLE
Argument 1 passed to findPREG() must be of the type array

### ISSUE THREAD

**Issue by ghost** [PocketMine/PocketBurger#1]
Command run: `php burger/munch.php --output output.json burger/libminecraftpe.asm`

Error:

```
Catchable fatal error: Argument 1 passed to findPREG() must be of the type array, null given, called in C:\Users\Documents\php\burger\src\parser.php on line 142 and defined in C:\Users\Documents\php\burger\src\parser.php on line 3
```

**Comment by shoghicp** [comment]
Hey!

Thank you for using this, but PocketBurger won't work with newer versions. I'm working on other scripts that will make this easier in the future :)

**Comment by ghost** [comment]
@shoghicp Thank you for your response! When do you think you will have this new version done? And in the mean time do you have any up-to-date documentation that I can refer to for the MCPE protocol?

**Comment by shoghicp** [comment]
For RakNet there is https://github.com/PocketMine/RakLib and for the MCPE protocol there is https://github.com/PocketMine/PocketMine-MP/tree/master/src/pocketmine/network/protocol

**Comment by ghost** [comment]
@shoghicp I forgot to ask, but what does the PocketMine team use for collecting protocol information?
